services:
  machine_a:
    build: Machine/
    deploy:
      mode: replicated
      replicas: 2
    environment:
      MACHINE_TYPE: A
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: "mysql+aiomysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD}
      RABBITMQ_USE_TLS: ${RABBITMQ_USE_TLS}
      RABBITMQ_CA_CERT_PATH: ${RABBITMQ_CA_CERT_PATH}
      RABBITMQ_CLIENT_CERT_PATH: ${RABBITMQ_CLIENT_CERT_PATH}
      RABBITMQ_CLIENT_KEY_PATH: ${RABBITMQ_CLIENT_KEY_PATH}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    volumes:
      - machine-db:/database
      - ./ssl/:${RABBITMQ_CERT_PATH}:ro
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/machine/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  machine_b:
    build: Machine/
    deploy:
      mode: replicated
      replicas: 2
    environment:
      MACHINE_TYPE: B
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: "mysql+aiomysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD}
      RABBITMQ_USE_TLS: ${RABBITMQ_USE_TLS}
      RABBITMQ_CA_CERT_PATH: ${RABBITMQ_CA_CERT_PATH}
      RABBITMQ_CLIENT_CERT_PATH: ${RABBITMQ_CLIENT_CERT_PATH}
      RABBITMQ_CLIENT_KEY_PATH: ${RABBITMQ_CLIENT_KEY_PATH}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    volumes:
      - machine-db:/database
      - ./ssl/:${RABBITMQ_CERT_PATH}:ro
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/machine/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  order:
    build: Order/
    volumes:
      - order-db:/database
      - ./ssl/:${RABBITMQ_CERT_PATH}:ro
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: "mysql+aiomysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD}
      RABBITMQ_USE_TLS: ${RABBITMQ_USE_TLS}
      RABBITMQ_CA_CERT_PATH: ${RABBITMQ_CA_CERT_PATH}
      RABBITMQ_CLIENT_CERT_PATH: ${RABBITMQ_CLIENT_CERT_PATH}
      RABBITMQ_CLIENT_KEY_PATH: ${RABBITMQ_CLIENT_KEY_PATH}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/order/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  delivery:
    build: Delivery/
    volumes:
      - delivery-db:/database
      - ./ssl/:${RABBITMQ_CERT_PATH}:ro
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: "mysql+aiomysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD}
      RABBITMQ_USE_TLS: ${RABBITMQ_USE_TLS}
      RABBITMQ_CA_CERT_PATH: ${RABBITMQ_CA_CERT_PATH}
      RABBITMQ_CLIENT_CERT_PATH: ${RABBITMQ_CLIENT_CERT_PATH}
      RABBITMQ_CLIENT_KEY_PATH: ${RABBITMQ_CLIENT_KEY_PATH}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/deliveries/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  payment:
    build: Payment/
    volumes:
      - payment-db:/database
      - ./ssl/:${RABBITMQ_CERT_PATH}:ro
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: "mysql+aiomysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD}
      RABBITMQ_USE_TLS: ${RABBITMQ_USE_TLS}
      RABBITMQ_CA_CERT_PATH: ${RABBITMQ_CA_CERT_PATH}
      RABBITMQ_CLIENT_CERT_PATH: ${RABBITMQ_CLIENT_CERT_PATH}
      RABBITMQ_CLIENT_KEY_PATH: ${RABBITMQ_CLIENT_KEY_PATH}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/payment/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  logger:
    build: Logger/
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./ssl/:${RABBITMQ_CERT_PATH}:ro
    ports:
      - "8100:8000"
    environment:
      PYTHONUNBUFFERED: 1
      MONGODB_URL: mongodb://mongodb:27017
      MONGODB_DATABASE: logger
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD}
      RABBITMQ_USE_TLS: ${RABBITMQ_USE_TLS}
      RABBITMQ_CA_CERT_PATH: ${RABBITMQ_CA_CERT_PATH}
      RABBITMQ_CLIENT_CERT_PATH: ${RABBITMQ_CLIENT_CERT_PATH}
      RABBITMQ_CLIENT_KEY_PATH: ${RABBITMQ_CLIENT_KEY_PATH}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/logger/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  warehouse:
    build: Warehouse/
    volumes:
      - warehouse-db:/database
      - ./ssl/:${RABBITMQ_CERT_PATH}:ro
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: "mysql+aiomysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWD: ${RABBITMQ_PASSWD}
      RABBITMQ_USE_TLS: ${RABBITMQ_USE_TLS}
      RABBITMQ_CA_CERT_PATH: ${RABBITMQ_CA_CERT_PATH}
      RABBITMQ_CLIENT_CERT_PATH: ${RABBITMQ_CLIENT_CERT_PATH}
      RABBITMQ_CLIENT_KEY_PATH: ${RABBITMQ_CLIENT_KEY_PATH}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/warehouse/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  haproxy:
    build: haproxy/
    ports:
      - "443:443"
      - "80:80"
      - "8404:8404"
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    volumes:
      - ./haproxy/nat.cfg.template:/usr/local/etc/haproxy/haproxy.cfg.template:ro
      - ./ssl:/etc/ssl/certs:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pgrep", "haproxy" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/log_aggregation --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  machine-db:
  order-db:
  delivery-db:
  payment-db:
  warehouse-db:
