services:
  haproxy:
    build: haproxy/
    ports:
      - "443:443"
      - "80:80"
      - "8404:8404"
    environment:
      AUTH_HOST: ${AUTH_HOST}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
      OTHERS_HOST: ${OTHERS_HOST}
    volumes:
      - ./haproxy/nat.cfg.template:/usr/local/etc/haproxy/haproxy.cfg.template:ro
      - ./ssl:/etc/ssl/certs:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pgrep", "haproxy" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s