{
 "title": "Logs Dashboard",
 "description": "Logs Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Containers",
    "query": {}
   },
   { "name": "filter_msj", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Type Level Log",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({container_name=~\"$container\"} |~ `(?i)$filter_msj` | logfmt | level =~ `warn|error` [$__auto]))"
    }
   ]
  },
  {
   "title": "Type Level Log",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container_name=~\"$container\"} |~ `(?i)$filter_msj` | logfmt | method =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Status Response",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({container_name=~\"$container\"} |~ `(?i)$filter_msj` | logfmt | status =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logger Timeline",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(container_name) (count_over_time({container_name=~\"$container\"} |~ `(?i)$filter_msj` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logger Visualizer",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "{container_name=~\"$container\"} |~ `(?i)$filter_msj` | logfmt"
    }
   ]
  }
 ]
}